sudo: required
apt:
  update: true
services:
- docker
cache:
  directories:
  - "$CACHE_DIR"
before_script:
# Disable default postgres
# http://docs.travis-ci.com/user/database-setup/#MySQL
- sudo /etc/init.d/postgresql stop
script:
- docker-compose -f docker-compose.test.yml up --abort-on-container-exit --exit-code-from django