version: '3.6'

services:
  db:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'postgres'
    volumes:
    - ./postgres_data:/var/lib/postgresql/data/
  django:
    build: .
    ports:
      - "8000:8000"
    volumes:
    - .:/home/poet
    env_file: poet.env
    command: ["./wait-and-run.sh"]
    depends_on:
      - db
