version: '3'
services:
  db:
    restart: always
    image: postgres:12-alpine
    env_file: /home/poetica/environ
    volumes:
    - /home/www/pg_data:/var/lib/postgresql/data/
  django:
    restart: always
    build:
      target: app
      context: .
    ports:
      - "8000:8000"
    volumes:
      - /home/www/media:/home/www/media
      - /home/www/static:/home/www/static
      - /home/www/poet/socket:/home/poetica/socket
    env_file: /home/poetica/environ
    command: ["./wait-and-run.sh"]
    depends_on:
      - db
