version: '3'
services:
  db:
    image: postgres:12-alpine
    env_file: poet.env
  django:
    build: .
    ports:
      - "8000:8000"
    volumes:
    - .:/home/poet
    env_file: poet.env
    command: ["./wait-and-test.sh"]
    depends_on:
      - db


