version: '3.4'

services:
  db:
    image: postgres:10.5-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'postgres'
  django:
    build: .
    ports:
      - "8000:8000"
    volumes:
    - .:/code
    env_file: poet.env
    command: ["./wait-and-test.sh"]
    depends_on:
      - db


