version: '3'
services:
  db:
    image: postgres:12-alpine
    env_file: poet.env
    volumes:
    - ./postgres_data:/var/lib/postgresql/data/
  django:
    build: .
    ports:
      - "8000:8000"
    volumes:
    - .:/home/poetica
    env_file: poet.env
    command: ["./wait-and-run.sh"]
    depends_on:
      - db
