version: '3'
services:
  db:
    image: postgres:12-alpine
    env_file: poet.env
    volumes:
    - ./postgres_data:/var/lib/postgresql/data/
  django:
    build: .
    ports:
      - "8000:8000"
    env_file: poet.env
    volumes:
      - ./app:/home/poetica/app
      - ./static:/home/poetica/static
      - ./config:/home/poetica/config
      - ./locale:/home/poetica/locale
      - ./test:/home/poetica/test
    command: ["./wait-and-run.sh"]
    depends_on:
      - db
