# Generated by Django 2.2.24 on 2021-09-23 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_add_mm_work_collection_rel'),
    ]

    operations = [
        migrations.RunSQL("""
        WITH inserts AS (
            SELECT 
                id from_work,
                in_collection to_collection,
                track_number
            FROM poet_work
            WHERE in_collection IS NOT NULL
        ) 
        INSERT INTO poet_work_to_collection_rel (from_work, to_collection, track_number) SELECT * FROM inserts;
        """),
    ]
