# Generated by Django 2.2.24 on 2021-09-23 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_populate_work_collection_rel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalwork',
            name='in_collection',
        ),
        migrations.RemoveField(
            model_name='historicalwork',
            name='track_number',
        ),
        migrations.RemoveField(
            model_name='work',
            name='in_collection',
        ),
        migrations.RemoveField(
            model_name='work',
            name='track_number',
        ),
    ]
