# Generated by Django 2.2.24 on 2021-10-22 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_remove_in_collection_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entitytoworkrel',
            options={'managed': True, 'verbose_name': 'role', 'verbose_name_plural': 'Roles'},
        ),
        migrations.AlterModelOptions(
            name='historicalentitytoworkrel',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical role'},
        ),
        migrations.AlterModelOptions(
            name='historicalworktocollection',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Playlist'},
        ),
        migrations.AlterModelOptions(
            name='worktocollection',
            options={'managed': True, 'verbose_name': 'Playlist', 'verbose_name_plural': 'Playlists'},
        ),
        migrations.AlterField(
            model_name='entitytoworkrel',
            name='relationship',
            field=models.CharField(choices=[('Composición', 'Composición'), ('Lectura en voz alta', 'Lectura en voz alta'), ('Interpretación musical', 'Interpretación musical'), ('Ingeniería de sonido', 'Ingeniería de sonido'), ('Producción', 'Producción'), ('Dirección', 'Dirección'), ('Post-producción', 'Post-producción'), ('Auxiliar de sonido', 'Auxiliar de sonido'), ('Contribuidor', 'Contribuidor'), ('Publicador', 'Publicador'), ('Traducción', 'Traducción')], default='Lectura en voz alta', max_length=256, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='historicalentitytoworkrel',
            name='relationship',
            field=models.CharField(choices=[('Composición', 'Composición'), ('Lectura en voz alta', 'Lectura en voz alta'), ('Interpretación musical', 'Interpretación musical'), ('Ingeniería de sonido', 'Ingeniería de sonido'), ('Producción', 'Producción'), ('Dirección', 'Dirección'), ('Post-producción', 'Post-producción'), ('Auxiliar de sonido', 'Auxiliar de sonido'), ('Contribuidor', 'Contribuidor'), ('Publicador', 'Publicador'), ('Traducción', 'Traducción')], default='Lectura en voz alta', max_length=256, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='historicalworkcollection',
            name='origin',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Provenance'),
        ),
        migrations.AlterField(
            model_name='workcollection',
            name='origin',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Provenance'),
        ),
    ]
