name: test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install test dependencies and run tests
      run:  docker-compose -f docker-compose.test.yml up --abort-on-container-exit --exit-code-from django
